server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql:///shop
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: goods_service
  registry:
    address: zookeeper://192.168.226.180:2181
  protocol:
    port: -1
  #当前服务作为消费者时，不检查提供者是否启动
  consumer:
    check: false